// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.web.converter;

import com.atlasck.web.converter.AnswerConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AnswerConverter_Roo_Configurable {
    
    declare @type: AnswerConverter: @Configurable;
    
}
