// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.web;

import com.atlasck.web.AnswerBean;
import java.io.Serializable;

privileged aspect AnswerBean_Roo_Serializable {
    
    declare parents: AnswerBean implements Serializable;
    
    private static final long AnswerBean.serialVersionUID = 1L;
    
}
