// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.web;

import com.atlasck.web.QuestionBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect QuestionBean_Roo_Configurable {
    
    declare @type: QuestionBean: @Configurable;
    
}
