// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.web;

import com.atlasck.web.QuestionBean;
import java.io.Serializable;

privileged aspect QuestionBean_Roo_Serializable {
    
    declare parents: QuestionBean implements Serializable;
    
    private static final long QuestionBean.serialVersionUID = 1L;
    
}
