// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.web;

import com.atlasck.web.VisitorBean;
import java.io.Serializable;

privileged aspect VisitorBean_Roo_Serializable {
    
    declare parents: VisitorBean implements Serializable;
    
    private static final long VisitorBean.serialVersionUID = 1L;
    
}
