// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.backend.domain;

import com.atlasck.backend.domain.VisitorsDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VisitorsIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VisitorsIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VisitorsIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: VisitorsIntegrationTest: @Transactional;
    
    @Autowired
    private VisitorsDataOnDemand VisitorsIntegrationTest.dod;
    
    @Test
    public void VisitorsIntegrationTest.testCountVisitorses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to initialize correctly", dod.getRandomVisitors());
        long count = com.atlasck.backend.domain.Visitors.countVisitorses();
        org.junit.Assert.assertTrue("Counter for 'Visitors' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VisitorsIntegrationTest.testFindVisitors() {
        com.atlasck.backend.domain.Visitors obj = dod.getRandomVisitors();
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to provide an identifier", id);
        obj = com.atlasck.backend.domain.Visitors.findVisitors(id);
        org.junit.Assert.assertNotNull("Find method for 'Visitors' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Visitors' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VisitorsIntegrationTest.testFindAllVisitorses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to initialize correctly", dod.getRandomVisitors());
        long count = com.atlasck.backend.domain.Visitors.countVisitorses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Visitors', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.atlasck.backend.domain.Visitors> result = com.atlasck.backend.domain.Visitors.findAllVisitorses();
        org.junit.Assert.assertNotNull("Find all method for 'Visitors' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Visitors' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VisitorsIntegrationTest.testFindVisitorsEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to initialize correctly", dod.getRandomVisitors());
        long count = com.atlasck.backend.domain.Visitors.countVisitorses();
        if (count > 20) count = 20;
        java.util.List<com.atlasck.backend.domain.Visitors> result = com.atlasck.backend.domain.Visitors.findVisitorsEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Visitors' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Visitors' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VisitorsIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to initialize correctly", dod.getRandomVisitors());
        com.atlasck.backend.domain.Visitors obj = dod.getNewTransientVisitors(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Visitors' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Visitors' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VisitorsIntegrationTest.testRemove() {
        com.atlasck.backend.domain.Visitors obj = dod.getRandomVisitors();
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Visitors' failed to provide an identifier", id);
        obj = com.atlasck.backend.domain.Visitors.findVisitors(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Visitors' with identifier '" + id + "'", com.atlasck.backend.domain.Visitors.findVisitors(id));
    }
    
}
