// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.domain;

import com.atlasck.domain.Answer;

privileged aspect Answer_Roo_JavaBean {
    
    public String Answer.getAnswer() {
        return this.answer;
    }
    
    public void Answer.setAnswer(String answer) {
        this.answer = answer;
    }
    
}
