// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.domain;

import com.atlasck.domain.Visitor;

privileged aspect Visitor_Roo_JavaBean {
    
    public String Visitor.getIpAddress() {
        return this.ipAddress;
    }
    
    public void Visitor.setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }
    
}
