// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.domain;

import com.atlasck.domain.Question;
import com.atlasck.domain.QuestionIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect QuestionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: QuestionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: QuestionIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: QuestionIntegrationTest: @Transactional;
    
    @Test
    public void QuestionIntegrationTest.testCountQuestions() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        long count = Question.countQuestions();
        Assert.assertTrue("Counter for 'Question' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void QuestionIntegrationTest.testFindQuestion() {
        Question obj = dod.getRandomQuestion();
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Question' failed to provide an identifier", id);
        obj = Question.findQuestion(id);
        Assert.assertNotNull("Find method for 'Question' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Question' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void QuestionIntegrationTest.testFindAllQuestions() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        long count = Question.countQuestions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Question', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Question> result = Question.findAllQuestions();
        Assert.assertNotNull("Find all method for 'Question' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Question' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void QuestionIntegrationTest.testFindQuestionEntries() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        long count = Question.countQuestions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Question> result = Question.findQuestionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Question' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Question' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void QuestionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", dod.getRandomQuestion());
        Question obj = dod.getNewTransientQuestion(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Question' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Question' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Question' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void QuestionIntegrationTest.testRemove() {
        Question obj = dod.getRandomQuestion();
        Assert.assertNotNull("Data on demand for 'Question' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Question' failed to provide an identifier", id);
        obj = Question.findQuestion(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Question' with identifier '" + id + "'", Question.findQuestion(id));
    }
    
}
