// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.domain;

import com.atlasck.domain.Visitor;
import com.atlasck.domain.VisitorDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect VisitorDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VisitorDataOnDemand: @Component;
    
    private Random VisitorDataOnDemand.rnd = new SecureRandom();
    
    private List<Visitor> VisitorDataOnDemand.data;
    
    public Visitor VisitorDataOnDemand.getNewTransientVisitor(int index) {
        Visitor obj = new Visitor();
        setCreatedAt(obj, index);
        setEmail(obj, index);
        setIpAddress(obj, index);
        setNickname(obj, index);
        setUpdatedAt(obj, index);
        return obj;
    }
    
    public void VisitorDataOnDemand.setCreatedAt(Visitor obj, int index) {
        Date createdAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedAt(createdAt);
    }
    
    public void VisitorDataOnDemand.setEmail(Visitor obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 255) {
            email = new Random().nextInt(10) + email.substring(1, 255);
        }
        obj.setEmail(email);
    }
    
    public void VisitorDataOnDemand.setIpAddress(Visitor obj, int index) {
        String ipAddress = "ipAddress_" + index;
        if (ipAddress.length() > 255) {
            ipAddress = ipAddress.substring(0, 255);
        }
        obj.setIpAddress(ipAddress);
    }
    
    public void VisitorDataOnDemand.setNickname(Visitor obj, int index) {
        String nickname = "nickname_" + index;
        if (nickname.length() > 255) {
            nickname = nickname.substring(0, 255);
        }
        obj.setNickname(nickname);
    }
    
    public void VisitorDataOnDemand.setUpdatedAt(Visitor obj, int index) {
        Date updatedAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedAt(updatedAt);
    }
    
    public Visitor VisitorDataOnDemand.getSpecificVisitor(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Visitor obj = data.get(index);
        Integer id = obj.getId();
        return Visitor.findVisitor(id);
    }
    
    public Visitor VisitorDataOnDemand.getRandomVisitor() {
        init();
        Visitor obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return Visitor.findVisitor(id);
    }
    
    public boolean VisitorDataOnDemand.modifyVisitor(Visitor obj) {
        return false;
    }
    
    public void VisitorDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Visitor.findVisitorEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Visitor' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Visitor>();
        for (int i = 0; i < 10; i++) {
            Visitor obj = getNewTransientVisitor(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
