// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.domain;

import com.atlasck.domain.VisitorIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect VisitorIntegrationTest_Roo_Configurable {
    
    declare @type: VisitorIntegrationTest: @Configurable;
    
}
