package com.atlasck.domain;

// Generated Oct 28, 2010 9:14:28 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

/**
 * Answer generated by hbm2java
 */
public class Answer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private Question question;
	private String answer;
	private Date createdAt;
	private Date updatedAt;

	public Answer() {
	}

	public Answer(Question question) {
		this.question = question;
	}

	public Answer(Question question, String answer, Date createdAt,
			Date updatedAt) {
		this.question = question;
		this.answer = answer;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Question getQuestion() {
		return this.question;
	}

	public void setQuestion(Question question) {
		this.question = question;
	}

	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
