// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.backend.domain;

import java.lang.String;

privileged aspect Answers_Roo_JavaBean {

    public String Answers.getAnswer() {
        return this.answer;
    }

    public void Answers.setAnswer(String answer) {
        this.answer = answer;
    }

}
