// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.backend.domain;

import java.lang.String;

privileged aspect Questions_Roo_JavaBean {
    
    public String Questions.getQuestion() {
        return this.question;
    }
    
    public void Questions.setQuestion(String question) {
        this.question = question;
    }
    
}
