// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atlasck.backend.domain;

import com.atlasck.backend.domain.AnswersDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AnswersIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AnswersIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AnswersIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AnswersIntegrationTest: @Transactional;
    
    @Autowired
    private AnswersDataOnDemand AnswersIntegrationTest.dod;
    
    @Test
    public void AnswersIntegrationTest.testCountAnswerses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to initialize correctly", dod.getRandomAnswers());
        long count = com.atlasck.backend.domain.Answers.countAnswerses();
        org.junit.Assert.assertTrue("Counter for 'Answers' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AnswersIntegrationTest.testFindAnswers() {
        com.atlasck.backend.domain.Answers obj = dod.getRandomAnswers();
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to provide an identifier", id);
        obj = com.atlasck.backend.domain.Answers.findAnswers(id);
        org.junit.Assert.assertNotNull("Find method for 'Answers' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Answers' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AnswersIntegrationTest.testFindAllAnswerses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to initialize correctly", dod.getRandomAnswers());
        long count = com.atlasck.backend.domain.Answers.countAnswerses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Answers', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.atlasck.backend.domain.Answers> result = com.atlasck.backend.domain.Answers.findAllAnswerses();
        org.junit.Assert.assertNotNull("Find all method for 'Answers' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Answers' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AnswersIntegrationTest.testFindAnswersEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to initialize correctly", dod.getRandomAnswers());
        long count = com.atlasck.backend.domain.Answers.countAnswerses();
        if (count > 20) count = 20;
        java.util.List<com.atlasck.backend.domain.Answers> result = com.atlasck.backend.domain.Answers.findAnswersEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Answers' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Answers' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AnswersIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to initialize correctly", dod.getRandomAnswers());
        com.atlasck.backend.domain.Answers obj = dod.getNewTransientAnswers(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Answers' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Answers' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AnswersIntegrationTest.testRemove() {
        com.atlasck.backend.domain.Answers obj = dod.getRandomAnswers();
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to initialize correctly", obj);
        java.lang.Integer id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Answers' failed to provide an identifier", id);
        obj = com.atlasck.backend.domain.Answers.findAnswers(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Answers' with identifier '" + id + "'", com.atlasck.backend.domain.Answers.findAnswers(id));
    }
    
}
