package com.atlasck.domain;

// Generated Oct 28, 2010 9:14:28 AM by Hibernate Tools 3.3.0.GA

/**
 * CurrentVersion generated by hbm2java
 */
public class CurrentVersion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
	private String username;
	private String passwd;
	private Boolean maintenance;
	private Boolean httpAuth;

	public CurrentVersion() {
	}

	public CurrentVersion(String username, String passwd, Boolean maintenance,
			Boolean httpAuth) {
		this.username = username;
		this.passwd = passwd;
		this.maintenance = maintenance;
		this.httpAuth = httpAuth;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPasswd() {
		return this.passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public Boolean getMaintenance() {
		return this.maintenance;
	}

	public void setMaintenance(Boolean maintenance) {
		this.maintenance = maintenance;
	}

	public Boolean getHttpAuth() {
		return this.httpAuth;
	}

	public void setHttpAuth(Boolean httpAuth) {
		this.httpAuth = httpAuth;
	}

}
